name: mi_proyecto
version: '1.0'
config-version: 2

profile: mi_proyecto  

model-paths: ["models"]
analysis-paths: ["analysis"]
test-paths: ["tests"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  mi_proyecto:
    staging:
      +materialized: view
    marts:
      +materialized: table
